// Emits the DRAFT consumer ontology ontology/zcode-loop.ttl from the runtime's own event enums.
// The object mapping policy below is the reviewable part of the draft; everything else is read
// from vendor/zcode.cjs. Run: bun scripts/gen-zcode-loop.ts  (writes ontology/zcode-loop.ttl)
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { readRuntimeEvents, wireOf } from "./zcode-events.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// Envelope-only event that stream-json appends after the last turn event (not in the wire enum).
const STREAM_ONLY = ["result"];

// Wire events deliberately kept out of the OCEL log, with the reason.
const UNMAPPED: Record<string, string> = {
  "part.delta": "token-level content delta; the surrounding part.upserted and tool.updated events carry the process step",
  result: "end-of-run summary envelope; duplicates turn.completed and adds no process step"
};

type Rel = { object: string; qualifier: string; path: string };
const OBJECTS = ["session", "turn", "tool_call", "model_request", "subagent", "permission"] as const;
const QUALIFIERS: Record<(typeof OBJECTS)[number], string> = {
  session: "in_session",
  turn: "in_turn",
  tool_call: "about_tool_call",
  model_request: "about_model_request",
  subagent: "by_subagent",
  permission: "about_permission"
};
const PATHS: Record<(typeof OBJECTS)[number], string> = {
  session: "sessionId",
  turn: "turnId",
  tool_call: "payload.toolCallId",
  model_request: "payload.requestId",
  subagent: "payload.agentId",
  permission: "payload.requestId"
};

// Which objects each wire event relates. session + turn always; the rest where the payload carries the id.
function objectsFor(wire: string): (typeof OBJECTS)[number][] {
  const base: (typeof OBJECTS)[number][] = ["session", "turn"];
  if (wire === "session.updated") return [...base, "tool_call", "model_request", "subagent"];
  if (wire === "tool.updated" || wire === "streamRecovery.updated") return [...base, "tool_call"];
  if (wire.startsWith("permission.") || wire.startsWith("userInput.")) return [...base, "permission"];
  return base;
}

const snake = (wire: string) => wire.replace(/\./g, "_").replace(/[A-Z]/g, (c) => "_" + c.toLowerCase());
const local = (s: string) => s.replace(/[^A-Za-z0-9]+/g, "-");
const q = (s: string) => JSON.stringify(s);

const events = readRuntimeEvents();
const wires = [...events.wire, ...STREAM_ONLY];

const out: string[] = [];
const w = (s = "") => out.push(s);

w("# DRAFT consumer ontology for the zcode agent runtime loop.");
w("# Generated by scripts/gen-zcode-loop.ts from vendor/zcode.cjs (internal enum W, wire enum, wire projection).");
w("# Review status: DRAFT. Object paths for the app-server subscription are UNVERIFIED (no live capture).");
w("@prefix zl: <https://zcode.dev/ontology/zcode-loop#> .");
w("@prefix pi: <https://ggen.dev/ontology/process-intelligence#> .");
w("@prefix st: <https://ggen.dev/ontology/state-transition#> .");
w("@prefix es: <https://ggen.dev/ontology/evidence-standing#> .");
w("@prefix sp: <http://seanchatmangpt.github.io/packs/shacl-projection#> .");
w("@prefix sh: <http://www.w3.org/ns/shacl#> .");
w("@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .");
w("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .");
w("@prefix ex: <https://zcode.dev/ontology/zcode-loop/shape#> .");
w();
w("# ===== chain policy (sha256; Bun 1.3.7 has no BLAKE3, no new deps) =====");
w('zl:ChainPolicy a pi:ChainPolicy ; pi:hashAlgorithm "sha256" ; pi:targetLanguage "ts" , "py" , "rs" , "ex" .');
w('zl:StChainPolicy a st:ChainPolicy ; st:chosenAlgo "sha256" ; st:policyPrecedence 10 ; st:policyLanguage "ts" , "py" , "rs" , "ex" .');
w("zl:EsChainPolicy a es:ChainPolicy ; es:hashAlgorithm es:Sha256 ; es:canonicalization es:CanonLinesV1 ;");
w('  es:genesisHash "0000000000000000000000000000000000000000000000000000000000000000" ; es:policyPrecedence 10 ;');
w("  es:targetLanguage es:LangTs , es:LangPy , es:LangRs , es:LangEx .");
w();
w("# ===== event sources =====");
w('zl:Source-StreamJson a pi:EventSource ; pi:sourceId "zcode_stream" ; pi:sourceKind "stream-json" ;');
w('  pi:nameField "type" ; pi:idField "eventId" ; pi:timeField "timestamp" ; pi:chainPolicy zl:ChainPolicy ;');
w('  rdfs:comment "zcode -p --output-format stream-json: one wire event per line (VERIFIED against a recorded real run)" .');
w('zl:Source-AppServer a pi:EventSource ; pi:sourceId "zcode_app_server" ; pi:sourceKind "app-server-subscription" ;');
w('  pi:nameField "params.type" ; pi:idField "params.eventId" ; pi:timeField "params.timestamp" ; pi:chainPolicy zl:ChainPolicy ;');
w('  rdfs:comment "zcode app-server event notifications: params carries the wire event (UNVERIFIED: no live subscription captured)" .');
w();
w("# ===== objects and qualifiers =====");
for (const o of OBJECTS) w(`zl:ObjectType-${o} a pi:ObjectType ; pi:typeId ${q(o)} .`);
for (const o of OBJECTS) w(`zl:Qualifier-${QUALIFIERS[o]} a pi:Qualifier ; pi:qualifierId ${q(QUALIFIERS[o])} .`);
w();
w("# ===== event types (one per wire event) =====");
for (const wire of wires) w(`zl:EventType-${local(wire)} a pi:EventType ; pi:typeId ${q(snake(wire))} .`);
w();

const sources = [
  { key: "Stream", iri: "zl:Source-StreamJson", prefix: "", wires },
  { key: "App", iri: "zl:Source-AppServer", prefix: "params.", wires: events.wire }
];
w("# ===== e2o relations (path into the raw record) =====");
for (const s of sources)
  for (const o of OBJECTS)
    w(`zl:Rel-${s.key}-${o} a pi:E2ORelation ; pi:relatesObjectType zl:ObjectType-${o} ; pi:hasQualifier zl:Qualifier-${QUALIFIERS[o]} ; pi:objectIdPath ${q(s.prefix + PATHS[o])} .`);
w();
w("# ===== mapping rules and runtime events =====");
for (const s of sources) {
  for (const wire of s.wires) {
    const ev = `zl:RuntimeEvent-${s.key}-${local(wire)}`;
    if (UNMAPPED[wire]) {
      w(`${ev} a pi:RuntimeEvent , pi:Unmapped ; pi:runtimeEventName ${q(wire)} ; pi:emittedBy ${s.iri} ; pi:unmappedReason ${q(UNMAPPED[wire])} .`);
      continue;
    }
    const rels = objectsFor(wire).map((o) => `zl:Rel-${s.key}-${o}`).join(" , ");
    w(`zl:Rule-${s.key}-${local(wire)} a pi:MappingRule ; pi:ruleId ${q(`${s.key.toLowerCase()}-${snake(wire)}`)} ; pi:fromSource ${s.iri} ; pi:sourceEvent ${q(wire)} ;`);
    w(`  pi:emitsEventType zl:EventType-${local(wire)} ; pi:hasRelation ${rels} .`);
    w(`${ev} a pi:RuntimeEvent ; pi:runtimeEventName ${q(wire)} ; pi:emittedBy ${s.iri} .`);
  }
}
w();
w("# ===== internal enum W -> wire projection (documentation of what each wire event folds) =====");
w("zl:InternalEvent a rdfs:Class .");
for (const [key, value] of Object.entries(events.internal)) {
  w(`zl:Internal-${key} a zl:InternalEvent ; zl:internalName ${q(value)} ; zl:foldsToWire ${q(wireOf(events, value))} .`);
}
w();
w("# ===== loop states: turn machine. Transition names equal OCEL event type ids, so replay folds the log. =====");
w('zl:TurnMachine a st:Machine ; st:machineName "ZcodeTurn" ; st:initial zl:TurnIdle .');
w('zl:TurnIdle a st:State ; st:inMachine zl:TurnMachine ; st:stateName "Idle" ; st:seq 0 .');
w('zl:TurnRunning a st:State ; st:inMachine zl:TurnMachine ; st:stateName "Running" ; st:seq 1 .');
w('zl:TurnCompleted a st:State ; st:inMachine zl:TurnMachine ; st:stateName "Completed" ; st:seq 2 .');
w('zl:TurnFailed a st:State ; st:inMachine zl:TurnMachine ; st:stateName "Failed" ; st:seq 3 .');
w('zl:TurnStart a st:Transition ; st:transitionName "turn_started" ; st:kind "advance" ; st:from zl:TurnIdle ; st:to zl:TurnRunning .');
w('zl:TurnComplete a st:Transition ; st:transitionName "turn_completed" ; st:kind "advance" ; st:from zl:TurnRunning ; st:to zl:TurnCompleted .');
w('zl:TurnFail a st:Transition ; st:transitionName "turn_failed" ; st:kind "abort" ; st:from zl:TurnRunning ; st:to zl:TurnFailed .');
w('zl:TurnStartAgain a st:Transition ; st:transitionName "turn_started" ; st:kind "loop" ; st:from zl:TurnCompleted ; st:to zl:TurnRunning .');
w('zl:TurnRetry a st:Transition ; st:transitionName "turn_started" ; st:kind "retry" ; st:from zl:TurnFailed ; st:to zl:TurnRunning .');
w();
w("# ===== receipt / event-record shapes (shacl-projection-pack -> zod + JSON Schema) =====");
w("ex:ReceiptEntryShape a sh:NodeShape ;");
w("  sh:property " + ["entry_id", "parent_hash", "phase", "standing", "subject", "action", "hash"].map((f) => `[ sh:path ex:${f} ; sh:datatype xsd:string ; sp:isPrimaryOutput true ]`).join(" ,\n    ") + " .");
w('zl:ReceiptEntry a sp:SchemaModel ; sp:className "ReceiptEntry" ; sp:derivedFromShape ex:ReceiptEntryShape .');
w("ex:OcelEventShape a sh:NodeShape ;");
w("  sh:property " + ["id", "type", "time"].map((f) => `[ sh:path ex:${f} ; sh:datatype xsd:string ; sp:isPrimaryOutput true ]`).join(" ,\n    ") + " .");
w('zl:OcelEventRecord a sp:SchemaModel ; sp:className "OcelEventRecord" ; sp:derivedFromShape ex:OcelEventShape .');
w();

mkdirSync(join(root, "ontology"), { recursive: true });
writeFileSync(join(root, "ontology", "zcode-loop.ttl"), out.join("\n"));
console.log(`wrote ontology/zcode-loop.ttl (${wires.length} wire events, ${Object.keys(events.internal).length} internal)`);
